---
title: "Cleaning & Wrangling"
format: html
editor: visual
---

```{r}
#| message: false

library(dplyr)
library(tidyr)
library(readr)

```
##Read in our dataa

```{r}
catch_original<-read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1")
```

## Explore 
```{r}
colnames(catch_original)
head(catch_original)
summary(catch_original)
unique(catch_original$Region)

```

#Clean and reshape data

```{r}
catch_data<- catch_original %>%
  select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)
head(catch_data)

catch_data<- catch_original %>%
  select(-All, -notesRegCode)
```

```{r}
glimpse(catch_data)

```
## Replace values in a column
```{r}
# Catch chinook column to numeric
catch_clean<- catch_data %>% 
  mutate(Chinook = as.numeric(Chinook))
```
```{r}
is.na(catch_clean$Chinook)
i <- which(is.na(catch_clean$Chinook))
i
catch_data[i,]
catch_clean<- catch_data %>% 
  mutate(Chinook = if_else(condition = Chinook == "I",
                          true= "1", 
                          false= Chinook),
         Chinook = as.numeric(Chinook))
```


##Reshaping
```{r}
head(catch_clean)
catch_long<- catch_clean %>% 
  pivot_longer(cols= -c(Region, Year),
               names_to = "species",
               values_to= "catch")
head(catch_long)
```

```{r}
catch_wide <- catch_long %>% 
  pivot_wider(names_from = species,
              values_from = catch)
head(catch_wide)
```

##Rename columns with rename()
```{r}
catch_long <-catch_long %>% 
  rename(catch_thousands = catch)
```

```{r}
catch_long <- catch_long %>% 
  mutate(catch = catch_thousands*1000)

```

##Summary stats using group_by() and summarize()
```{r}
#Get averge catch per region
mean_region<- catch_long %>% 
  group_by(Region) %>% 
  summarize(mean_catch = mean(catch))
head(mean_region)
```
```{r}
#number of rows for each group
n_region<- catch_long %>% 
  group_by(Region) %>% 
  summarize(n=n())
 
```


## Filtering rows using filter()
```{r}
sse_catch <- catch_long %>% 
  filter(Region == "SSE")
head(sse_catch)
```

```{r}
#filter to catches > 1e6 fish
many_fish<- catch_long %>% 
  filter(catch > 1e6)
head(many_fish)

#filter to just Chinook for SSE
just_Chinook <- catch_long %>% 
  filter(species == "Chinook" & Region == "SSE")
head(just_Chinook)

```

## Sorting data using arrange()
```{r}
mean_region <-catch_long %>% 
  group_by(Region) %>% 
  summarize(mean_catch = mean(catch)) %>% 
  arrange(mean_catch)

mean_region <-catch_long %>% 
  group_by(Region) %>% 
  summarize(mean_catch = mean(catch)) %>% 
  arrange(desc(mean_catch))
```

##Spliting and combining values in columns
```{r}
sites_df <- data.frame(site=c("HAW-101",
                                "HAW-103",
                                "OAH-320",
                                "OAH-219",
                                "MAU-039"))
split_df <- sites_df %>% 
  separate(site, c("island","site_numer"), "-")

cities_df <- data.frame(city = c("Juneau AK",
                                 "Sitka AK",
                                 "Anchorage AK"))
split_cities <- cities_df %>% 
  separate(city, c("city","state"), " ")


```



```{r}
data_df<-data.frame(
  year=c("1930", "1930", "1930"),
  month=c("12","12","12"),
  day=c("14","15","16")
)

dates_unite<-data_df %>% 
  unite(date, year, month, day, sep="-")
head(dates_unite)
```

```{r}
catch_original<-read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1")

mean_region <- catch_original %>%
  select(-All, -notesRegCode) %>% 
  mutate(Chinook = ifelse(Chinook == "I", 1, Chinook)) %>% 
  mutate(Chinook = as.numeric(Chinook)) %>% 
  pivot_longer(-c(Region, Year), 
               names_to = "species", 
               values_to = "catch") %>%
  mutate(catch = catch*1000) %>% 
  group_by(Region) %>% 
  summarize(mean_catch = mean(catch)) %>% 
  arrange(desc(mean_catch))

head(mean_region)
```


˜˜
